#!/bin/sh

exec 2>&1
exec chpst -e env \
  podman run --rm -it --name "mk2-db-devel" \
    -p 5432:5432 \
    -e TZ \
    -e "POSTGRES_*" \
    -v ../../data:/var/lib/postgresql/data \
  docker.io/postgres:18-alpine
